apiVersion: apps/v1
kind: Deployment
metadata:
  name: indikaapp01
spec:
  selector:
    matchLabels:
      app: indikaapp01
  template:
    metadata:
      labels:
        app: indikaapp01
    spec:
      containers:
<<<<<<< HEAD
      - name: indikaapp01
=======
      - name: sidapp01
>>>>>>> 5fde3c5963d72a6162b0959d7d075ef738bcf712
        image: sbacr02.azurecr.io/indikaapp01:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5178
